# Generated by Django 5.1.3 on 2024-11-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icecream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icecream_name', models.CharField(max_length=100)),
                ('icecream_description', models.TextField(default='icecream description')),
                ('icecream_price', models.PositiveIntegerField(default=0)),
                ('icecream_image', models.ImageField(upload_to='icecreams/')),
            ],
        ),
    ]
