# Generated by Django 5.1.3 on 2024-11-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecream', '0003_rename_catergory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='', upload_to='category/'),
        ),
    ]
